### ISSUE TITLE
Add project scope

### ISSUE THREAD

**Issue by fulldecent** [jennijuju/ATS041AionFungibleTokenReferenceImplementation#1]
Please state the goals of this project.

Is this intended to develop a reference implementation?

A reference implementation is created differently than a non-reference implementation. For one, a reference implementation does not add opinionated features

Knowing if this is a reference implementation will help contributors to contribute to this project.

**Comment by jennijuju** [comment]
Thank you for the suggestion! I will add it this week!

**Comment by jennijuju** [comment]
Added.
