### ISSUE TITLE
ATS using interface feedback

### ISSUE THREAD

**Issue by fulldecent** [jennijuju/ATS041AionFungibleTokenReferenceImplementation#14]
- [ ] Should Java DocBlocks be added to the interface the implementation or both?
- [ ] What is the best name for the reference implementation? Recommending `token-contract` rather than using the name of the standard inside the name. Referencing a best practice here https://github.com/0xcert/ethereum-erc721/blob/master/src/contracts/tokens/nf-token.sol

**Comment by jennijuju** [comment]
Implementation has been updated to the structure as discussed in the meeting on Aug 2nd, 2019. Please take a look at the latest version(hopefully the last version!), which is in master.
